### ISSUE TITLE
 Class 'Twig_Filter_Function' not found

### ISSUE THREAD

**Issue by KoljaL** [AndiLeni/pico_edit#4]
Hey Andi

I installed your plugin in the alpha Version of PicoCMS3 ang get this Error when calling the Editor:

```
Fatal error: Uncaught Error: Class 'Twig_Filter_Function' not found in /www/htdocs/domain.de/plugins/pico_edit/pico_edit.php:37 
Stack trace: 
#0 /www/htdocs/domain.de/vendor/picocms/pico/lib/AbstractPicoPlugin.php(101): Pico_Edit->onPageRendering(Object(Twig\Environment), Array, 'index.twig') 
#1 /www/htdocs/domain.de/plugins/PicoDeprecated/PicoDeprecated.php(319): AbstractPicoPlugin->handleEvent('onPageRendering', Array) 
#2 /www/htdocs/domain.de/plugins/PicoDeprecated/lib/AbstractPicoPluginApiCompatPlugin.php(81): PicoDeprecated->triggerEvent(1, 'onPageRendering', Array) 
#3 /www/htdocs/domain.de/plugins/PicoDeprecated/plugins/PicoPluginApi1CompatPlugin.php(258): AbstractPicoPluginApiCompatPlugin->triggerEvent('onPageRendering', Array) 
#4 /www/htdocs/domain.de/plugins/PicoDeprecated/lib/AbstractPicoCompatPlugin.php(74): PicoPluginApi1CompatPlugin->onPageRendering('index.twig', Array) 
#5 /www/htdocs/domain.de/plugins/PicoDeprecated/lib in /www/htdocs/domain.de/plugins/pico_edit/pico_edit.php on line 37
```

I just comment the Line 37 out:
```//    $twig_editor->addFilter('var_dump', new Twig_Filter_Function('var_dump')); ```
and the Editor ist working.

The same solution works with this error:
``` Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/domain.de/plugins/PicoPagesList/PicoPagesList.php:67) in /www/htdocs/domain/plugins/pico_edit/pico_edit.php on line 33```

Thank you for this needfull Plugin :-)

**Comment by AndiLeni** [comment]
Hey, 

I'm glad you like my plugin.

Unfortunately I'm not working with PicoCMS anymore and as far as I can see Pico 3 is in a very early stage of development.

If you like, you are welcome to create a pull request, which I will merge as soon as version 3 is stable.
